### PR TITLE
Added endpoint for net profit margin

### LINKED ISSUE #308: [Feature] Adding endpoint for profit margin
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.
I want to add new endpoint for calculating profit margin. Profit margin is a financial ratio that measures the percentage of profit earned in relation to its revenue.
I would like to work on this feature under GSSoC'23. Thank you!

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

### PR DESCRIPTION
**Pull request by ramya-kallam**
Fixes #308

### CODE REVIEW

**Comment by ighoshsubho** [comment]
The calculation seems quite straight forward try to implement this -> Net profit = Revenue/Sales + Income from other sources – Cost of Goods Sold – Operating Expenses – Other Expenses – Interest – Depreciation – Taxes

**Comment by ramya-kallam** [comment]
Net profit margin=(Revenue-cost of goods sold-operating and other expenses-interest-taxes)/(Revenue)
Is this fine?

> The calculation seems quite straight forward try to implement this -> Net profit = Revenue/Sales + Income from other sources – Cost of Goods Sold – Operating Expenses – Other Expenses – Interest – Depreciation – Taxes

**Comment by ighoshsubho** [comment]
Yup its fine!

**Comment by ramya-kallam** [comment]
Made the changes. Please review.

**Comment by ighoshsubho** [comment]
Congrats @ramya-kallam 🎉, your PR got merged! Star this repo and keep contributing like this in gssoc'23.

**Pull request merged**
