### PR TITLE
[ADDED]: Stock-Price-Prediction

### LINKED ISSUE #366: [Feature] Stock Price Prediction
## Are you adding a new feature?
- [X] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [X] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [X] NO

## Describe your feature/enhancement.

Machine learning has significant applications in the stock price prediction. In this machine learning project, we will be talking about predicting the returns on stocks. This is a very complex task and has uncertainties. We will develop this project into two parts:

First, we will learn how to predict stock price using the LSTM neural network.
Then we will build a dashboard using Plotly dash for stock analysis.
## Can you add the feature by yourself?

- [X] YES
- [ ] NO

### PR DESCRIPTION
**Pull request by Killer2OP**
# Stock Price Prediction
Machine learning has significant applications in the stock price prediction. In this  we are talking about predicting the returns on stocks.

## CLOSES ISSUE
Closes #366 

https://github.com/Clueless-Community/fintech-api/assets/111378171/49dd9652-0180-4adf-a462-c3ea10450df7

### CODE REVIEW

**Comment by Killer2OP** [comment]
@ighoshsubho Please review this PR and merge it.

**Comment by ighoshsubho** [comment]
Please check the CONTRIBUTIONS.md and make a fresh PR

**Comment by ighoshsubho** [comment]
Like how are you thinking of showing this in this API? And you have added some miscellaneous files along with the major changes, please remove it with gitignore.

**Comment by Killer2OP** [comment]
Ok :)

**Pull request closed without merging**
