### PR TITLE
added inventory shrinkage rate and markup _percentage endpoint

### LINKED ISSUE #39: Add Calculate Inventory Shrinkage Endpoint
Inventory shrinkage formula can be used if you want to figure out the percentage of inventory your business is losing.

### LINKED ISSUE #40: Add an endpoint to calculate markup percentage
If you need help setting your products’ prices, you can try using the markup formula. The markup percentage shows you how much more you sell offerings for than what they cost.

### PR DESCRIPTION
**Pull request by chandansgowda**
Closes #39 and Closes #40

### CODE REVIEW

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
Include your endpoint in `ENDPOINTS.md` file.

**Comment by chandansgowda** [comment]
Hey @nikhil25803 
I have made the necessary changes and also pushed code to close issue #40 also. Please review.
Thanks

**Review by nikhil25803 — APPROVED** [review]
Chnages approved.

**Comment by nikhil25803** [comment]
Congrats @chandansgowda  🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow these steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/)
3. Go to the profile section from the top right-hand corner.



Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard!

And don’t forget to share your achievement with your friends.

**Pull request merged**
