### PR TITLE
[Fixes: #414] Added Endpoint to Calculate MIRR

### LINKED ISSUE #414: [Feature] Modified Internal Rate of Return (MIRR)
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.
I want to add an endpoint for Modified Internal Rate of Return (MIRR).

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

### PR DESCRIPTION
**Pull request by ritik48**
This pr fixes #414 
Added endpoint to calculate Modified Internal Rate of Return

### CODE REVIEW

**Comment by ritik48** [comment]
@ighoshsubho please review this pr

**Comment by ritik48** [comment]
@ighoshsubho please review this pr

**Comment by ritik48** [comment]
@ighoshsubho please review this pr

**Comment by ighoshsubho** [comment]
Great @ritik48! Your PR got merged!

Keep contributing like this in GSSOC'23. 🚀

**Pull request merged**
