### PR TITLE
Policy premium endpoint is added

### PR DESCRIPTION
**Pull request by shraddha761**
Issue reference - #416

### CODE REVIEW

**Comment by shraddha761** [comment]
@ighoshsubho please review my pr

**Comment by shraddha761** [comment]
@ighoshsubho I have resolve merge conflict please review

**Comment by shraddha761** [comment]
@ighoshsubho Thank you for solving for mistakes

**Comment by ighoshsubho** [comment]
Good @shraddha761! Your PR got merged! Keep contributing in Fintech API repo like this.

**Pull request merged**
