### PR TITLE
Rate of return calculator is added

### PR DESCRIPTION
**Pull request by shraddha761**
Issue reference - #403

### CODE REVIEW

**Comment by ighoshsubho** [comment]
Other than this there are no changes needed @shraddha761. Make these changes and I'll merge it right away.

**Comment by shraddha761** [comment]
@ighoshsubho what changes i need to made. I resolve the merge conflict

**Comment by ighoshsubho** [comment]
In the latest commit you made changes in the defensive interval ratio task and not in the rate of return I was expecting. Please do the needful and I will merge. For any help you can reach me out over main, discord or in my socials. Thanks.

**Comment by shraddha761** [comment]
@ighoshsubho Apologize but I don't know how this happen

**Pull request closed without merging**
