### PR TITLE
added some important functions

### PR DESCRIPTION
**Pull request by shivvamm**
relate to  issue ##296
Present Value (PV)
Net Present Value (NPV)
Internal Rate of Return (IRR)
Return on Assets (ROA)
Return on Equity (ROE)
Debt Ratio
Equity Ratio
Times Interest Earned (TIE) Ratio
Working Capital Ratio
Dividend Discount Model (DDM)

### CODE REVIEW

**Comment by ighoshsubho** [comment]
@shivvamm you did use functions but they are not in functions .py and ENDPOINTS are also not updated, you can check the contributing guidelines before making a PR. Thanks.

**Comment by shivvamm** [comment]
Okay I'll check it and update It

**Comment by ighoshsubho** [comment]
Hey @shivvamm will you do it or should I close this PR and the issue?

**Comment by shivvamm** [comment]
Yes I will don't worry

**Comment by ighoshsubho** [comment]
Ok

**Comment by ighoshsubho** [comment]
Please check the CONTRIBUTIONS.md and make a fresh PR

**Comment by ighoshsubho** [comment]
Sorry @shivvamm it took 1 month for you to complete this endpoint. I'm closing this PR. For any further queries you can reach me out from my socials.

**Pull request closed without merging**
