### PR TITLE
fixing some bugs in endpoints ( Issue: #367 ) & Adding Endpoint to calculate Capital Asset Pricing Model (CAPM) ( Issue: #368) 

### PR DESCRIPTION
**Pull request by Codeansh**
Issue #367, bugs are removed.
Issue #368,  Add Endpoint to calculate Capital Asset Pricing Model (CAPM).

### CODE REVIEW

**Comment by ighoshsubho** [comment]
Everything looks ok, just confirm me with this sharpe_ratio.

**Comment by Codeansh** [comment]
Actually in the "helpers/functions.py" file function "sharpe_ratio" was defined twice ( at line 248 and line 1774 ). Due to the duplicate function, the endpoint was not working as expected. The first function is working correctly so I removed the duplicate function ( at line 1774 ). Now the endpoint is working correctly.

fintest

**Comment by ighoshsubho** [comment]
> Actually in the "helpers/functions.py" file function "sharpe_ratio" was defined twice ( at line 248 and line 1774 ). Due to the duplicate function, the endpoint was not working as expected. The first function is working correctly so I removed the duplicate function ( at line 1774 ). Now the endpoint is working correctly.
> 
> fintest

Sounds good! Congrats @Codeansh, your PR got merged! Keep contributing like this in GSSOC'23

**Comment by Codeansh** [comment]
> > Actually in the "helpers/functions.py" file function "sharpe_ratio" was defined twice ( at line 248 and line 1774 ). Due to the duplicate function, the endpoint was not working as expected. The first function is working correctly so I removed the duplicate function ( at line 1774 ). Now the endpoint is working correctly.
> > fintest
> 
> Sounds good! Congrats @Codeansh, your PR got merged! Keep contributing like this in GSSOC'23

Thanks @ighoshsubho.

**Pull request merged**
