### PR TITLE
Add an endpoint to calculate Loan EMI #13

### PR DESCRIPTION
**Pull request by DarK-VEnOM-16**
image

Created a function to calculate Loan Emi
Parameter Taken:
principle_amount: float, 
annual_rate: float,
months: int

Return format
{
            "Tag": "Loan Emi",
            "Princiapl amount borrowed": principle_amount,
            "Annual Rate of interest": annual_rate,
            "Total number of monthly payments": months,
            "EMI": f"{emi}%",
            "Total Amount Payble": f"{emi*months}%",
            "Interest amount": f"{emi*months-principle_amount}%"
        }

### CODE REVIEW

**Review by nikhil25803 — CHANGES_REQUESTED** [review]

**Comment by nikhil25803** [comment]
Hey @DarK-VEnOM-16, requested some changes. Also, include your endpoint in the `ENDPOINTS.md` file.

**Comment by DarK-VEnOM-16** [comment]
@nikhil25803  Added /loan_emi to Endpoints.md Corrected the response output, and merged the branch conflicts

**Review by nikhil25803 — APPROVED** [review]
Chnages made

**Comment by nikhil25803** [comment]
Congrats 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow these steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/)
3. Go to the profile section from the top right-hand corner.



Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard!

And don’t forget to share your achievement with your friends.

**Pull request merged**
