### PR TITLE
added new helper function to calculate capital_asset_pricing_model

### PR DESCRIPTION
**Pull request by ShamanthVallem**
Created a new helper function that can calculate the **capital asset pricing model** by taking risk_free_interest_rate, beta_of_security, and expected_market_return as inputs.

### CODE REVIEW

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
Include the endpoint in `main.py` file and `ENDPOINTS.md` file too.

**Comment by ShamanthVallem** [comment]
Made changes to both endpoint.md and main.py files

**Comment by nikhil25803** [comment]
Congrats @ShamanthVallem 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow these steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/)
3. Go to the profile section from the top right-hand corner.



Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard!

And don’t forget to share your achievement with your friends.

**Review by nikhil25803 — COMMENTED** [review]
Changes approved

**Pull request merged**
