### PR TITLE
Resolved issues: 58 59 60 61

### PR DESCRIPTION
**Pull request by pundarikaksha7**

### CODE REVIEW

**Comment by pundarikaksha7** [comment]
Have resolved multiple Issues.

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
Include the endpoints in the `ENDPOINTS.md` file, with sample input and output.

**Comment by nikhil25803** [comment]
Requested some changes and also there are some conflicts. Please look into it.
@pundarikaksha7

**Comment by pundarikaksha7** [comment]
Done

**Comment by nikhil25803** [comment]
@pundarikaksha7 | You still haven't added the endpoints in `ENDPOINTS.md`

**Comment by pundarikaksha7** [comment]
@nikhil25803 I did, its in another PR

**Pull request merged**
