### PR TITLE
added Endpoint to calculate Auto Lease

### PR DESCRIPTION
**Pull request by helloshiv01**
Performed calculations in the function.py file and Created the endpoint auto-lease in the main.py

### CODE REVIEW

**Comment by itsmegarvi** [comment]
mate you didn't add it in ENDPOINTS.md

**Comment by helloshiv01** [comment]
added now

**Comment by ighoshsubho** [comment]
Before reviewing and merging I would suggest you write a comment on the issue so that I can assign you to this issue @helloshiv01 .

**Comment by helloshiv01** [comment]
Done

**Comment by ighoshsubho** [comment]
Congrats 🎉 @helloshiv01, your PR got merged. To be eligible for the swags from ClueLess. Follow the steps mentioned.

1. Star this repository. ⭐
2. SignIn / SignUp in [ClueLess Website](https://www.clueless.tech/).
3. Go to the profile section from the top right-hand corner.
4. Comment your profile URL under this comment tagging the person who merged your PR.

And don’t forget to share your achievement with your friends.

**Comment by helloshiv01** [comment]
thank you @ighoshsubho i have star the repo but could not open the website.Can you please add swoc label on the above issue and close it.Also update my score for swoc

**Comment by ighoshsubho** [comment]
Sure!

**Comment by helloshiv01** [comment]
Also add my score label as well update my score in swoc score sheet.

**Pull request merged**
