### PR TITLE
Endpoint to calculate College Cost

### PR DESCRIPTION
**Pull request by filza2112**
I have created the Endpoint to calculate college expenses 

*Please give feedback and let me know if any changes are required*

### CODE REVIEW

**Comment by ighoshsubho** [comment]
There seems to be a conflict @filza2112, please check.

**Comment by filza2112** [comment]
Conflict resolved. please check

**Comment by ighoshsubho** [comment]
Great @filza2112, Your PR has been successfully merged, to be eligible for swags, please like this repo.

**Comment by filza2112** [comment]
Okay thank you @ighoshsubho

**Pull request merged**
