### PR TITLE
Issue 4 - add certificate of deposit (CD) helper and endpoint

### PR DESCRIPTION
**Pull request by yixin0829**
Implemented helper function for #4 and tested with Postman (see screenshot):
- A GET endpoint is also added to `main.py` named `\certificate_of_deposit` 
- Added helper function `certificate_of_deposit()` in `function.py`
- Pytest may be added in this PR or another issue should be opened (let me know your thoughts!)

image

### CODE REVIEW

**Comment by Jan729** [comment]
> Pytest may be added in this PR or another issue should be opened (let me know your thoughts!)

#8 adds pytest, so we can say this PR depends on #8.

**Comment by nikhil25803** [comment]
Hey @yixin0829, there are some merge conflicts. Please do resolve them first.

**Comment by nikhil25803** [comment]
Congrats 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow these steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [ClueLess Website](https://www.clueless.tech/)
3. Go to the profile section from the top right-hand corner.



Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard!

And don’t forget to share your achievement with your friends.

**Comment by yixin0829** [comment]
Ops was just trying to fix the merge conflicts. Thanks for merging! @nikhil25803

**Comment by nikhil25803** [comment]
@yixin0829, I just merged a PR before this that's why there was a conflict. So solved it :)

**Pull request merged**
