### PR TITLE
new helper function for roi and add pytest to repository (for testing FAST endpoints)

### PR DESCRIPTION
**Pull request by mymyxtran**
Issue link: [Create an endpoint to calculate ROI (Return on Investment) #3](https://github.com/Clueless-Community/fintech-api/issues/3)

- Tested the output using various inputs with pytest file test_main.py (new file added in this PR).
- Added updates to documentation for fintech-api/ENDPOINTS.md 
- Added section in CONTRIBUTING.md under > Folder Structure to have test_main.py and how to run and install
 
Screen Shot 2022-12-03 at 1 26 11 PM

### CODE REVIEW

**Comment by mymyxtran** [comment]
- Let me know if you would prefer for me to remove the test files and other changes I created, so that there is just the ROI function and no tests OR if would like it restructured.
- This is my first open-source contribution, so please let me know what I can do. Thanks!

**Comment by nikhil25803** [comment]
Wait, as Codepeak'22 will start on December 5. I will merge the PRs from that day only.

**Comment by mymyxtran** [comment]
oh, so I should re-make this pr on dec 5? :)

**Comment by nikhil25803** [comment]
No no, leave it.

**Comment by mymyxtran** [comment]
okay, thank you

**Comment by nikhil25803** [comment]
Congrats 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow these steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [ClueLess Website](https://www.clueless.tech/)
3. Go to the profile section from the top right-hand corner.



Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard!

And don’t forget to share your achievement with your friends.

**Pull request merged**
