### PR TITLE
Added sharpe ratio function

### PR DESCRIPTION
**Pull request by Abhinavcode13**
Added Sharpe ration function
Added the endpoints for this function and required tags and parameters
Added requirements.

closes issue number #318

### CODE REVIEW

**Comment by ighoshsubho** [comment]
Congrats @Abhinavcode13, your PR got merged! star this repo and keep contributing like this in GSSOC'23

**Comment by Abhinavcode13** [comment]
please give a label to it @ighoshsubho level3 as given in issue

thanks

**Comment by Abhinavcode13** [comment]
@ighoshsubho ??

**Comment by Abhinavcode13** [comment]
labels required to count in contributions for gssoc 23 @ighoshsubho :) 😄

**Pull request merged**
