### PR TITLE
[Fixes: #414] Added Endpoint to Calculate MIRR

### LINKED ISSUE #414: [Feature] Modified Internal Rate of Return (MIRR)
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.
I want to add an endpoint for Modified Internal Rate of Return (MIRR).

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

### PR DESCRIPTION
**Pull request by ritik48**
This pr fixes #414
Added endpoint to calculate Modified Internal Rate of Return

### CODE REVIEW

**Comment by ritik48** [comment]
@ighoshsubho please review this pr

**Comment by ighoshsubho** [comment]
You have not made any changes to the reviews which I did request. Any updates?

**Comment by ritik48** [comment]
@ighoshsubho sorry what updates are you talking about, I don't get it.

**Comment by ighoshsubho** [comment]
> @ighoshsubho sorry what updates are you talking about, I don't get it.

I'm talking abt the reviews I requested, is it all done?

**Comment by ritik48** [comment]
@ighoshsubho yes I have made the required changes.

**Comment by ighoshsubho** [comment]
The changes aren't reflected. maybe its better if you can make a new pr. Will be more clean.

**Comment by ritik48** [comment]
@ighoshsubho alright, I will create a new pr.

**Comment by ighoshsubho** [comment]
Thanks @ritik48, just make a new one and I'll merge once approved!

**Pull request closed without merging**
