### PR TITLE
feat: add codeql workflow

### PR DESCRIPTION
**Pull request by harmeetsingh11**
### Related Issues or bug
This PR resolves issue: #362 

### Files added
- `.github/workflows/codeql.yml`

Please review this PR.
Thanks

### CODE REVIEW

**Comment by ighoshsubho** [comment]
Please check the CONTRIBUTIONS.md and make a fresh PR

**Comment by ighoshsubho** [comment]
Congrats @harmeetsingh11 🎉, Your PR got merged! Keep contributing like this in GSSOC'23.

**Comment by bhavya1857** [comment]
is this issue closed @ighoshsubho then?

**Comment by ighoshsubho** [comment]
> is this issue closed @ighoshsubho then?

Yup its done!

**Comment by ighoshsubho** [comment]
> is this issue closed @ighoshsubho then?

Yup its done!

**Pull request merged**
