### PR TITLE
Issue  #184 Adding endpoint to caclculate Balloon Loan

### PR DESCRIPTION
**Pull request by itsmegarvi**
I have implemented the Balloon Loan payment formula and it is working alright

image

I seem to have messed with merging the conflicts, sorry about that. Please tell me if I can correct this

### CODE REVIEW

**Comment by itsmegarvi** [comment]
Seems like I managed to get rid of the conflicts, sorry about that

**Comment by ighoshsubho** [comment]
Sure no issue!

**Comment by ighoshsubho** [comment]
@itsmegarvi you can even test this with the test.py file, you might get more sure about the results thereafter!

**Comment by ighoshsubho** [comment]
Congrats 🎉 @itsmegarvi, your PR got merged. To be eligible for the swags from ClueLess. Follow the steps mentioned.

1. Star this repository. ⭐
2. SignIn / SignUp in [ClueLess Website](https://www.clueless.tech/).
3. Go to the profile section from the top right-hand corner.
4. Comment your profile URL under this comment tagging the person who merged your PR.

And don’t forget to share your achievement with your friends.

**Pull request merged**
