### PR TITLE
[Feature]Endpoint for calculating of Net income, Break-even point, Days sales in inventory ratio, Cash ratio

### PR DESCRIPTION
**Pull request by suvamita**
Please check my PR. I made a little mistake in the Day SalesIinventory Ratio formula. 
Days Sales Inventory Ratio=(Average Inventory/Cost Of Goods Sold)*No Of Days
The above formula is correct for calculating Days Sales Inventory Ratio.

### CODE REVIEW

**Comment by ighoshsubho** [comment]
You have committed 4k+ files, might forgot to specify them in gitignore! Please do the needful and commit accordingly!

**Comment by suvamita** [comment]
Actually I didn't understand what should I need to specify in gitignore. Please help me .

**Comment by ighoshsubho** [comment]
Just include all the names of files and folders that are not a part of our repo now! And you will be good to go.

In that way you can ignore all the temporary modules.

**Comment by suvamita** [comment]
I am unable to add all the files and folders . Can I delete this main_1 branch and make a new branch then make new pull request for this issue?

**Comment by ighoshsubho** [comment]
Please check the CONTRIBUTIONS.md and make a fresh PR

**Pull request closed without merging**
